name: Petri Jarvinen
favicon: null
layout_spectrum: 0.88181
typography_spectrum: 1
title: Petri Jarvinen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8ffff'
    - '#00010b'
    - '#353f3e'
    - '#788387'
    - '#dfbf76'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
