typography_spectrum: 1
color:
  brandColors:
    - '#f8ffff'
    - '#00010b'
    - '#353f3e'
    - '#788387'
    - '#dfbf76'
  brandStrength: 0.1875
  lightness: 0.4375
  rhythmicContrast: 0.75
  saturation: 0.3125
opengraph:
  appId: 'https://www.facebook.com/jarvinen.se'
layout_spectrum: 0.359375
analytics:
  facebook: '1534878076823920'
  google: UA-79784396-1
  twitter: null
author:
  name: petri jarvinen
  email: petri@jarvinen.se
  url: 'http://petrijarvinen.com'
name: Petri Jarvinen
cta: {}
navigation: []
title: It's not over until you win!
description: Really.
purpose: []
