typography_spectrum: 1
color:
  brandColors:
    - '#f8ffff'
    - '#00010b'
    - '#353f3e'
    - '#788387'
    - '#dfbf76'
  brandStrength: 0.1875
  lightness: 0.4375
  rhythmicContrast: 0.75
  saturation: 0.3125
opengraph: {}
layout_spectrum: 0.359375
analytics:
  facebook: '1534878076823920'
  google: UA-79784396-1
  twitter: null
author:
  name: petri jarvinen
  email: petri@jarvinen.se
  url: 'http://petrijarvinen.com'
name: Petri Jarvinen
cta: {}
navigation:
  - name: Follow These
    id: 952e6c78-451a-42e3-8fdd-b548e6bf900e
    type: content
  - name: Follow These
    id: a81d1a8a-b998-4ee2-851e-74bd45c96596
    type: content
title: PJ
description: Really.
purpose: []
