typography_spectrum: 1
color:
  brandColors:
    - '#f8ffff'
    - '#00010b'
    - '#353f3e'
    - '#788387'
    - '#dfbf76'
  brandStrength: 0.1875
  lightness: 0.4375
  rhythmicContrast: 0.75
  saturation: 0.3125
opengraph: {}
layout_spectrum: 0.359375
analytics: {}
name: Petri Jarvinen
cta: {}
purpose: []
